Feature/redis part 1
adityasatrio/golang-echo-boilerplate pull request #29
Opened 2023-06-30 21:09 UTC by miraj90van

- add config for redis
- add cache service & unit test
- implement cache in system-parameter

2023-07-03 03:21 UTC, adityasatrio commented on cmd/main.go
> +	//signal.Notify(quit, os.Interrupt)
ini uncomment

2023-07-03 03:23 UTC, adityasatrio commented on cmd/main.go
> +	redisConnection := redis.NewRedisClient()
apakah butuh defer close redis connection

2023-07-03 03:25 UTC, adityasatrio commented on configs/redis/connection_redis.go
> +	addr := viper.GetString("cache.configs.redis.host") + ":" + viper.GetString("cache.configs.redis.port")
bisa contoh yg ini ya
```
dsn := fmt.Sprintf("%s:%s@tcp(%s:%s)/%s?parseTime=true",
		viper.GetString("db.configs.username"),
		viper.GetString("db.configs.password"),
		viper.GetString("db.configs.host"),
		viper.GetString("db.configs.port"),
		viper.GetString("db.configs.database"))
```

2023-07-03 03:27 UTC, adityasatrio commented on globalutils/cache_key_util.go
> +	ApplicationName = "echo-boilerplate"
ambil dari viper 
```
	appName := viper.GetString("application.name")
```

2023-07-03 03:29 UTC, adityasatrio commented on globalutils/cache_key_util.go
> +package globalutils
di move ke package "system_parameter"

```
system_parameter_cache_key.go
```

2023-07-03 03:32 UTC, adityasatrio commented on internal/applications/cache/caching_service_impl.go
> +		fmt.Println("Failed for marshaling data:", err)
```suggestion
		log.error("Failed for marshaling data:", err)
```
pakai log nya echo ya

2023-07-03 03:35 UTC, adityasatrio commented on internal/applications/cache/caching_service_impl.go
> +}
move ke dalam 1 package ama cache, tp di file berbeda 
```
lz4_compressor.go
```

2023-07-03 03:37 UTC, adityasatrio commented on internal/applications/system_parameter/service/system_parameter_service_impl.go
> +	_, err = s.cache.Create(ctx, globalutils.CacheKeySysParamWithId(result.ID), result, time.Hour*3)
viper cache config 
```
cache.ttl.short.period  = 3 jam
cache.ttl.medium.period  = 24 jam 
cache.ttl.long.period = 3 hari


```

2023-07-03 03:45 UTC, adityasatrio commented on internal/applications/cache/caching_service_impl.go
> +	return data, nil
```
if  result == redis.Nil
     return nil, nil
 
```

2023-07-03 03:46 UTC, adityasatrio commented on internal/applications/system_parameter/service/system_parameter_service_impl.go
> +	}
redis.Nil itu hanya boleh di handle di domain si service cache 
si implementor tdk perlu, di hanya perlu tau hasil

2023-07-03 03:47 UTC, adityasatrio commented on internal/applications/system_parameter/service/system_parameter_service_impl.go
> +	}
sama seperti di atas

2023-07-03 03:50 UTC, adityasatrio requested changes
minor changes

2023-07-04 05:01 UTC, miraj90van commented on cmd/main.go
> +	//signal.Notify(quit, os.Interrupt)
sudah di uncomment

2023-07-04 05:01 UTC, miraj90van commented on cmd/main.go
> +	redisConnection := redis.NewRedisClient()
sudah ditambahkan

2023-07-04 05:02 UTC, miraj90van commented on configs/redis/connection_redis.go
> +	addr := viper.GetString("cache.configs.redis.host") + ":" + viper.GetString("cache.configs.redis.port")
sudah ditambahkan

2023-07-04 05:05 UTC, miraj90van commented on internal/applications/system_parameter/service/system_parameter_service_impl.go
> +	}
done

2023-07-04 05:05 UTC, miraj90van commented on internal/applications/system_parameter/service/system_parameter_service_impl.go
> +	}
done

2023-07-04 05:05 UTC, miraj90van commented on internal/applications/system_parameter/service/system_parameter_service_impl.go
> +	_, err = s.cache.Create(ctx, globalutils.CacheKeySysParamWithId(result.ID), result, time.Hour*3)
done

2023-07-04 05:05 UTC, miraj90van commented on internal/applications/cache/caching_service_impl.go
> +}
done

2023-07-04 05:05 UTC, miraj90van commented on internal/applications/cache/caching_service_impl.go
> +		fmt.Println("Failed for marshaling data:", err)
done

2023-07-04 05:06 UTC, miraj90van commented on globalutils/cache_key_util.go
> +package globalutils
done

2023-07-04 05:08 UTC, miraj90van commented on internal/applications/system_parameter/service/system_parameter_cache_key.go
> +}
gw kurang sregg melihat code ini `configs.BuildConfigEnv()`
tapi ini perlu ditambahkan agar viper bisa digunakan di file ini 
gmana menurut lo mas @adityasatrio , apakah ada cara lain?

2023-07-04 06:29 UTC, adityasatrio commented on app.config.yml
> +    medium-period:  = 24 hour
```suggestion
    medium-period: 24 hour
```

2023-07-04 06:38 UTC, adityasatrio requested changes
feedback

2023-07-04 06:38 UTC, adityasatrio commented on app.config.yml
> +    medium-period:  = 24 hour
@miraj90van emg bs ya langsung pake day, hour etc gtu di config ?

2023-07-04 06:38 UTC, adityasatrio commented on configs/configuration_env.go
> +}
kenapa ini di define lagi ya ? kan redundant ama yg di `SetupConfigEnv()`

2023-07-04 06:38 UTC, adityasatrio commented on internal/applications/cache/cache_duration.go
> +	}
ini tuh kenapa ga langsung `viper.GetString("KEY")l` ya ? ada issue apa ya ?

2023-07-04 06:38 UTC, adityasatrio commented on internal/applications/cache/caching_service_impl.go
> +func NewCachingServiceImpl(redisClient *redis.Client) *CachingServiceImpl {
```suggestion
func NewCachingService(redisClient *redis.Client) *CachingServiceImpl {
```

2023-07-04 06:38 UTC, adityasatrio commented on internal/applications/system_parameter/service/system_parameter_cache_key.go
> +}
iya harus nya ga boleh sih, implementasi ini `configs.BuildConfigEnv()` harus nya redundant dengan yg ada di code `main.go` yaitu `setupConfigs`

nah ini butuh di define krn gagal di test atau sewaktu runtime ya ? klo gagal nya di test berarti yg di butuh kan helper utk test implementation nya.

tp klo gagal di runtime brrti utk AppName di config butuh di ubah strategy nya, jd global variable yg di define sebelum main function di `main.go`

2023-07-04 09:11 UTC, miraj90van commented on internal/applications/system_parameter/service/system_parameter_cache_key.go
> +}
use, global variable

2023-07-04 09:12 UTC, miraj90van commented on configs/configuration_env.go
> +}
done

2023-07-04 09:12 UTC, miraj90van commented on internal/applications/cache/caching_service_impl.go
> +func NewCachingServiceImpl(redisClient *redis.Client) *CachingServiceImpl {
ini default contructor buatan intellij, sudah disesuaikan

2023-07-04 09:13 UTC, miraj90van commented on internal/applications/cache/cache_duration.go
> +	}
sudah di sesuaikan

2023-07-04 09:13 UTC, miraj90van commented on app.config.yml
> +    medium-period:  = 24 hour
sudah disesuaikan

2023-07-05 02:39 UTC, adityasatrio requested changes
need confirmation and discussion

2023-07-05 02:39 UTC, adityasatrio commented on internal/applications/system_parameter/service/system_parameter_service_impl.go
> +	_, err = s.cache.Create(ctx, CacheKeySysParamWithId(result.ID), result, cache.CachingShortPeriod())
@miraj90van kek kurang elegan wkwkw, ya tp boleh lah

2023-07-05 02:39 UTC, adityasatrio commented on internal/applications/system_parameter/service/system_parameter_service_impl.go
> +		return nil, exceptions.NewBusinessLogicError(exceptions.EBL10006, err)
kek nya klo gagal create cache ga perlu error ga sih ?
yg penting ke DB udah masuk, terus pas di get di service function jg akan cek ada ga di cache, klo ga ada fallback di ke DB

palingan klo gagal nge-log aja

2023-07-05 02:39 UTC, adityasatrio commented on internal/applications/system_parameter/service/system_parameter_service_impl.go
>  	}
sama nih, ini err libs atau error create ya, si cache kan harus nya ga blh blocking system flow krn secondary layer data aja

2023-07-05 10:33 UTC, merged