Feature/ent transaction
adityasatrio/golang-echo-boilerplate pull request #7
Opened 2023-03-04 21:03 UTC by miraj90van

transaction

2023-03-13 01:24 UTC, adityasatrio commented on ent/schema/post.go
> +		field.Time("deleted_at").Optional().Nillable(),
```
// Fields of the System_parameter.
func (System_parameter) Fields() []ent.Field {
	schema := []ent.Field{
		field.String("key").NotEmpty().Unique(),
		field.String("value").NotEmpty(),
	}

	return helper.InitBaseSchema(schema)
}
```

pakai `InitBaseSchema` supaya semua nya sama

2023-03-13 01:27 UTC, adityasatrio commented on internal/applications/post/controller/post_controller.go
> +	created, err := c.service.Create(ctx.Request().Context(), *request)
```
	created, err := c.service.Create(ctx.Request().Context(), *request)
```

`request` kenapa pake pointer ya, menurut gw cukup passing by value nya aja krn ga bakal di modify lagi

2023-03-13 01:30 UTC, adityasatrio commented on internal/applications/post/dto/post_dto.go
> +	Post struct {
```suggestion
	PostResponse struct {
```

2023-03-13 01:34 UTC, adityasatrio requested changes
request minor changes

2023-03-17 20:00 UTC, miraj90van commented
close pr, use another pr

2023-03-17 20:00 UTC, closed without merging